### PR TITLE
Update TOC.md

### PR DESCRIPTION
**Pull request by TinaLiuGirl**
12:58

### CODE REVIEW

**Comment by TinaLiuGirl** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/TinaLiuGirl/TinaTest, working directory: W:\1pww-s, target branch: master, target branch commit: a09aea6828feeedba6f880e3b89bf4801bc7048b, source branch: Local4, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C24%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711240458285036-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=al8luIiCclLHHqsPbuVqrAgIp%2BTE%2BEuNoOEL5VTE9%2Fw%3D&st=2017-11-24T04%3A53%3A34Z&se=2017-12-25T04%3A58%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by TinaLiuGirl** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Docset4/TOC.md](https://github.com/TinaLiuGirl/TinaTest/blob/Local4/Docset4/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C24%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711240554058139-9%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0coR3wIef1CyVnxcofFb1l5%2Fvx3nf5FHBAEwrselfoM%3D&st=2017-11-24T05%3A49%3A42Z&se=2017-12-25T05%3A54%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by TinaLiuGirl** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change. 
 TOC File | This PR contains a change to the TOC file.

**Comment by TinaLiuGirl** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 TOC File | This PR contains a change to the TOC file. 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger17** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 TOC File | This PR contains a change to the TOC file. 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Pull request closed without merging**
