### PR TITLE
4:35

### PR DESCRIPTION
**Pull request by TinaLiuGirl**

### CODE REVIEW

**Comment by TinaLiuGirl** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/TinaLiuGirl/TinaTest, working directory: W:\3elo-s, target branch: master, target branch commit: 606fae235ceed8982d69b7b58223fbd519200ea6, source branch: Local4, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C22%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711220835584538-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jcxD0FWZKprBl%2BDM9UOwvydKAN1sSgSrxgmM8ZreWL8%3D&st=2017-11-22T08%3A31%3A03Z&se=2017-12-23T08%3A36%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by TinaLiuGirl** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Docset4/index.md](https://github.com/TinaLiuGirl/TinaTest/blob/Local4/Docset4/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C22%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711220920235708-6%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4xOjk9G0IRftej6KTVH704XfYnIEpDCkBWhYZ%2BEcdiM%3D&st=2017-11-22T09%3A16%3A04Z&se=2017-12-23T09%3A21%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TinaLiuGirl** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by PRMerger14** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 Index File | This PR contains a change to the index file.

**Comment by PRMerger14** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 Index File | This PR contains a change to the index file.

**Comment by PRMerger10** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 Index File | This PR contains a change to the index file.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 Index File | This PR contains a change to the index file.

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 Index File | This PR contains a change to the index file.

**Comment by PRMerger20** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 Index File | This PR contains a change to the index file.

**Comment by TinaLiuGirl** [comment]
## PRMerger Results
 | Issue | Resolution |
 --- | --- | 
 Index File | This PR contains a change to the index file.

**Pull request merged**
