### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by TinaLiuGirl**

### CODE REVIEW

**Comment by TinaLiuGirl** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/TinaLiuGirl/TinaTest, working directory: W:\wmig-s, target branch: master, target branch commit: 5349d4339f41041aad4edfc83cf7da9251a09b55, source branch: Local4, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C21%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711211012307731-4%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VNKaxSFUMdpN49g2Vt7omPwaX23Fh2HzA0RBdpdPcH8%3D&st=2017-11-21T10%3A07%3A36Z&se=2017-12-22T10%3A12%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TinaLiuGirl** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Docset4/index.md](https://github.com/TinaLiuGirl/TinaTest/blob/Local4/Docset4/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C21%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711211013022859-4%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hnB%2FkNV1H2VX2E9vAAi%2BXuLNcoCkT76fM63DAp5V5%2B4%3D&st=2017-11-21T10%3A08%3A41Z&se=2017-12-22T10%3A13%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by TinaLiuGirl** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Docset4/index.md](https://github.com/TinaLiuGirl/TinaTest/blob/Local4/Docset4/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C21%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711211013197014-4%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YrWjWCR3Fmbb3lqesx6nVrLgteWmyVxEN%2FKNiDXO7Qs%3D&st=2017-11-21T10%3A09%3A23Z&se=2017-12-22T10%3A14%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger18** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by PRMerger10** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Pull request closed without merging**
