### PR TITLE
1:51

### PR DESCRIPTION
**Pull request by TinaLiuGirl**
1:51

### CODE REVIEW

**Comment by TinaLiuGirl** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 128**: **[Error]** Pull content in folder W:\ehio-s\_themes failed. Error: remote: Repository not found. fatal: repository &#39;https://username:e1f1a4dcd22239323f9484683b0e3f8d5917063b@github.com/Microsoft/templates.docs.msft/&#39; not found 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C21%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711210551276006-3%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mmBbuuJ0tOROb4gaccfA66K5ZkLFJEacaZ3AXEPVUW0%3D&st=2017-11-21T05%3A47%3A03Z&se=2017-12-22T05%3A52%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TinaLiuGirl** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Docset4/index.md](https://github.com/TinaLiuGirl/TinaTest/blob/master/Docset4/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C21%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711210624316399-3%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yyoah6y3wpD2G5j0OFlXfij4%2FnOhH%2FI%2FDjHPP92ZtuA%3D&st=2017-11-21T06%3A20%3A10Z&se=2017-12-22T06%3A25%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by PRMerger20** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by PRMerger7** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by PRMerger13** [comment]
### PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by PRMerger17** [comment]
### PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Pull request closed without merging**
