### PR TITLE
Local4 11:31

### PR DESCRIPTION
**Pull request by TinaLiuGirl**

### CODE REVIEW

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by TinaLiuGirl** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Docset4/index.md](https://github.com/TinaLiuGirl/TinaTest/blob/Local4/Docset4/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C22%5Cd165304b-cbe5-a2bf-3b25-32c5e2321e9c%5CPullRequest%5C201711220331363435-5%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Pn6dUTZk7EY%2BScJ5xfUetsHNWH9gE8NM2744CVw4HMI%3D&st=2017-11-22T03%3A27%3A20Z&se=2017-12-23T03%3A32%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PRMerger6** [comment]
### :warning: PRMerger: Sign off requires successful build 
 
- You signed off, but the build has not completed or there are outstanding validation warnings. Please wait for the build to complete, and address any outstanding validation warnings. Then, you can sign off on the pull request.

**Comment by PRMerger14** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 Index File | This PR contains a change to the index file. 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger8** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change. 
 Index File | This PR contains a change to the index file.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Pull request merged**
